// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDweGasNqo4EabQZaSLtj3JO5K-hqDabT0',
    appId: '1:475087217355:web:4de684d9d2f719afb7f14e',
    messagingSenderId: '475087217355',
    projectId: 'messaging-app-6fe8b',
    authDomain: 'messaging-app-6fe8b.firebaseapp.com',
    storageBucket: 'messaging-app-6fe8b.firebasestorage.app',
    measurementId: 'G-57PP68X84T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiXK3xjlQv5lNknkYMoRJMOffGTyAIy0U',
    appId: '1:475087217355:android:a212bdb919f793c5b7f14e',
    messagingSenderId: '475087217355',
    projectId: 'messaging-app-6fe8b',
    storageBucket: 'messaging-app-6fe8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZTI9R1yy5dv-zCpfw62qhQUun0oaJrxg',
    appId: '1:475087217355:ios:a6202ba29e034914b7f14e',
    messagingSenderId: '475087217355',
    projectId: 'messaging-app-6fe8b',
    storageBucket: 'messaging-app-6fe8b.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZTI9R1yy5dv-zCpfw62qhQUun0oaJrxg',
    appId: '1:475087217355:ios:a6202ba29e034914b7f14e',
    messagingSenderId: '475087217355',
    projectId: 'messaging-app-6fe8b',
    storageBucket: 'messaging-app-6fe8b.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDweGasNqo4EabQZaSLtj3JO5K-hqDabT0',
    appId: '1:475087217355:web:f46be0b7077fc470b7f14e',
    messagingSenderId: '475087217355',
    projectId: 'messaging-app-6fe8b',
    authDomain: 'messaging-app-6fe8b.firebaseapp.com',
    storageBucket: 'messaging-app-6fe8b.firebasestorage.app',
    measurementId: 'G-KNEN648L67',
  );
}
